# Generated by Django 4.0 on 2021-12-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kakao_id', models.IntegerField()),
                ('nickname', models.CharField(max_length=500)),
                ('profile_img', models.URLField(max_length=1000)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
